services:
  postgres:
    image: postgres:15
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - appnet

  backend:
    build:
      context: ./backend
    env_file: .env
    environment:
      DATABASE_HOST: ${DATABASE_HOST}
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      PORT: ${PORT}
    ports:
      - "3002:3002"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.backend.rule=Host(`my-photo-album.pl`) && PathPrefix(`/api`)"
      - "traefik.http.routers.backend.entrypoints=websecure"
      - "traefik.http.services.backend.loadbalancer.server.port=3002"
      - "traefik.http.routers.backend.tls=true"
      - "traefik.http.routers.backend.middlewares=strip-api"
      - "traefik.http.middlewares.strip-api.stripprefix.prefixes=/api"
    depends_on:
      - postgres
    networks:
      - appnet

  frontend:
    build:
      context: ./frontend
      args:
        - NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
        - NEXT_PUBLIC_FRONTEND_URL=${NEXT_PUBLIC_FRONTEND_URL}
    env_file: .env
    environment:
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_FRONTEND_URL}
    ports:
      - "3000:3000"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend.rule=Host(`my-photo-album.pl`)"
      - "traefik.http.routers.frontend.entrypoints=websecure"
      - "traefik.http.services.frontend.loadbalancer.server.port=3000"
      - "traefik.http.routers.frontend.tls=true"
    depends_on:
      - backend
    networks:
      - appnet

  traefik:
    image: traefik:latest
    environment:
      - DOCKER_API_VERSION=1.44
    command:
      - --api.insecure=true
      - --providers.docker=true
      - --providers.file.filename=/certs/dynamic.yml
      - --entryPoints.web.address=:80
      - --entryPoints.websecure.address=:443
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080" # traefik dashboard (insecure)
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - traefik_lets_encrypt:/letsencrypt
      - ./traefik:/certs:ro
    networks:
      - appnet

volumes:
  pgdata:
  traefik_lets_encrypt:

networks:
  appnet:
    driver: bridge

